[package]
name = "cantan"
version = "0.1.0"
authors = ["luapix <luapixel@gmail.com>"]
edition = "2018"

[dependencies]
gc-arena = "0.2.0"
num-traits = "0.2.12"
once_cell = "1.4.1"
ordered-float = "2.0.0"
peg = "0.6.3"
rustyline = "6.2.0"
unicode-segmentation = "1.6.0"
unicode-xid = "0.2.1"
